### ISSUE TITLE
tryParse with scale does not round the value.

### ISSUE THREAD

**Issue by oakstair** [onepub-dev/fixed#10]
This test is failing.

Fixed gives '3.1415' which is wrong.

// Failing test
expect(Fixed.tryParse('3.1415926535897932', scale: 4).toString(), '3.1416');

**Comment by bsutton** [comment]
Thanks for raising the issue. I will try to have a look over the weekend.

**Comment by bsutton** [comment]
Can you confirm which version of fixed you are using?

**Comment by bsutton** [comment]
Found and fixed in 2.3.2.

Thanks for the contributions.
