### ISSUE TITLE
IntegerDivisionByZeroException when converting toInt from zero with default scale

### ISSUE THREAD

**Issue by dmitry-kotorov** [onepub-dev/fixed#11]
import 'package:fixed/fixed.dart';

void main() {
  Fixed zero = Fixed.fromInt(0);
  print(zero.toString());
  zero.toInt();
}

/Users/****/fvm/versions/stable/bin/cache/dart-sdk/bin/dart --enable-asserts /Users/****/StudioProjects/test/lib/main.dart
0.00
Unhandled exception:
IntegerDivisionByZeroException
#0      _BigIntImpl.~/ (dart:core-patch/bigint_patch.dart:1702:7)
#1      Fixed.toInt (package:fixed/src/fixed.dart:475:30)
#2      main (package:test_project/main.dart:7:8)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Process finished with exit code 255

**Comment by bsutton** [comment]
Thanks for the bug report.
I've released 2.3.3 with a fix.
