### ISSUE TITLE
`toInt` implementation wrong?

### ISSUE THREAD

**Issue by flodiebold** [onepub-dev/fixed#13]
https://github.com/onepub-dev/fixed/blob/d25fe302681b2f553dd4ec21ac9761eced4ceeec/lib/src/fixed.dart#L476

Am I completely misunderstanding what `toInt` is supposed to do, or should this rather be `BigInt.from(10).pow(scale)`?

**Comment by bsutton** [comment]
You are correct.

I've released 3.0.1 with your fixed applied and some additional unit tests.

Thanks!
