### ISSUE TITLE
Fixed.one docs say scale=2, but implementation uses scale=16

### ISSUE THREAD

**Issue by jaween** [onepub-dev/fixed#14]
The doc comment for `Fixed.one` and similar values say they use a `scale` of 2.
https://github.com/onepub-dev/fixed/blob/3cea81d7b4f2ecaebb5d03b7c40df99b149a91d9/lib/src/fixed.dart#L181-L191

but looking at the implementation it uses `Fixed.fromNum` with the default value for `scale` which is 16:
https://github.com/onepub-dev/fixed/blob/3cea81d7b4f2ecaebb5d03b7c40df99b149a91d9/lib/src/fixed.dart#L96-L105

**Comment by bsutton** [comment]
So the question is do we fix the doco or the implementation?

I'm inclined to fix the doc as that won't break anything.

Thoughts?

**Comment by jaween** [comment]
I agree that just updating the docs is the right approach, leaving the implementation as is.

At least until the next major version where you could make a breaking change, since I found it a surprising default for `Fixed.one.toString()` to be `"1.0000000000000000"` instead of `"1.00"`.

**Comment by bsutton** [comment]
updated doco in 4.1.1 to reflect that the scale is 16 not 2.
