### ISSUE TITLE
FixedParseException implements Exception instead of FixedException

### ISSUE THREAD

**Issue by jaween** [onepub-dev/fixed#17]
Hi again, still enjoying `fixed` :)

The package has a `FixedException` which says it's the "`Base exception of all exceptions thrown from the Fixed package`". But `Fixed.parse` can throw a `FixedParseException` which instead implements `Exception`.

`FixedParseException` should probably add `FixedException` to its implements clause (which is a non breaking change I believe). Then later in a major update remove `Exception` from its implements clause.

Another possibility would be to export the `FixedParseException` so consumers can catch it directly, and change the docs for `FixedException`.

**Comment by bsutton** [comment]
Fixed in 4.2.0.

I've changed the hierarchy.
exported all exceptions.
