### ISSUE TITLE
MIT or Proprietary?

### ISSUE THREAD

**Issue by jocubeit** [onepub-dev/fixed#8]
The license distributed with this package is MIT.

However, every file has a contradictory notice stating:
* Unauthorized copying of this file, via any medium is strictly prohibited
* Proprietary and confidential

This effectively renders the package completely unusable as the very act of installing this package from pub.dev means you're copying the files. The statements are in complete contradiction of the MIT open source license.

So which is it?  I'm confused.

**Comment by bsutton** [comment]
The code base is actually a mixed license.
There are significant portions copied from the pub command which come under
the MIT license whereas other parts are not.
So the code base is fully open source but only parts are FOSS.

I'm not quite certain what the license should look like but I will do some
reading and update the license.

appreciate the feedback.

Brett

**Comment by bsutton** [comment]
Sorry about the long delay on this one.

My original response actually pertained to another project.

The odd licenses in the code where the result of a way wood script that incorrectly updated fixed.

I've fixed these licenses to correctly reflect the MIT license.
